name: Update README ‚≠ê
on:
    schedule:
        - cron: "51 */4 * * *" # Every 4 hours
    workflow_dispatch:

jobs:
    update-readme:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v3
            - uses: k2bd/advent-readme-stars@v1
              with:
                  userId: 2869123
                  leaderboardId: 2869123
                  sessionCookie: ${{ secrets.AOC_SESSION }}
            - uses: stefanzweifel/git-auto-commit-action@v5 # use v5
              with:
                  commit_message: Update README stars
